In [8]:
import numpy as np

In [14]:
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights =   [[0.2,0.8,-0.5,1.0],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87],]

biases = [2,3,0.5]

weights2 =   [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13],]

biases2 = [-1,2,-0.5]

In [15]:
layer1_output = np.dot(inputs,np.array(weights).T) + biases
layer1_output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [16]:
layer2_output = np.dot(layer1_output,np.array(weights2).T) + biases2
layer2_output

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [17]:
np.random.seed(0)

In [18]:
X =  [[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]

In [42]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

In [43]:
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)


In [44]:
layer1.forward(X)

In [45]:
layer2.forward(layer1.output)

In [46]:
layer2.output

array([[-0.04928311, -0.05467371],
       [ 0.08558312,  0.13478291],
       [-0.04465149, -0.14341661]])