In [11]:
import math

In [12]:
layer_outputs = [4.8 , 1.21 , 2.385]
E = math.e

exp_values = [(E**i) for i in layer_outputs]
exp_values

[121.51041751873483, 3.353484652549023, 10.859062664920513]

In [13]:
normal_base = sum(exp_values)
normal_base

135.72296483620437

In [14]:
normal_values = [(i/normal_base) for i in exp_values]
normal_values

[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]

In [15]:
sum(normal_values)

0.9999999999999999

In [16]:
import numpy as np

In [18]:
exp_values2 = np.exp(layer_outputs)
exp_values2

array([121.51041752,   3.35348465,  10.85906266])

In [23]:
normal_base2 = np.sum(exp_values2)
normal_base2

135.7229648362044

In [24]:
normal_values2 = exp_values2/np.sum(exp_values2)
normal_values2

array([0.89528266, 0.02470831, 0.08000903])

In [25]:
sum(normal_values2)

0.9999999999999999

In [39]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [27]:
layer_outputs = [[4.8 , 1.21 , 2.385],
                 [8.9,-1.81,0.2],
                 [1.41,1.051,0.026]]

In [28]:
exp_values = np.exp(layer_outputs)
exp_values

array([[1.21510418e+02, 3.35348465e+00, 1.08590627e+01],
       [7.33197354e+03, 1.63654137e-01, 1.22140276e+00],
       [4.09595540e+00, 2.86051020e+00, 1.02634095e+00]])

In [36]:
v = np.sum(layer_outputs,axis=1,keepdims=True)
v

array([[8.395],
       [7.29 ],
       [2.487]])

In [38]:
normal_values = exp_values / v
normal_values

array([[1.44741415e+01, 3.99462138e-01, 1.29351551e+00],
       [1.00575769e+03, 2.24491271e-02, 1.67544960e-01],
       [1.64694628e+00, 1.15018504e+00, 4.12682327e-01]])

In [40]:
class Dense_Layer: 
    def __init__(self, n_inputs,n_neurons) -> None:
        self.weights = np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

In [41]:
class Softmax:
    def forward(self,inputs):
        exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        self.output = exp_values / np.sum(exp_values, axis=1, keepdims=True)

In [42]:
X,y = spiral_data(samples=100,classes=3)

In [46]:
dense1 = Dense_Layer(2,3)
activation1 = Softmax()

dense2 = Dense_Layer(3,3)
activation2 = Softmax()

In [47]:
dense1.forward(X)
activation1.forward(dense1.output)

In [48]:
dense2.forward(activation1.output)
activation2.forward(dense2.output)

In [49]:
activation2.output

array([[0.37162253, 0.34502697, 0.2833505 ],
       [0.3717491 , 0.3450697 , 0.2831812 ],
       [0.37182537, 0.34512267, 0.28305194],
       ...,
       [0.34002405, 0.3519243 , 0.30805165],
       [0.35910738, 0.36389834, 0.27699432],
       [0.3607768 , 0.36451572, 0.27470753]], dtype=float32)